### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by r-cemper** [pisani/OpenTelemetry#1]
#7 84.73 ☺chmod♦☺-R♣☺775☺sr/irissys/csp/irisapp/
#7 84.77 [opentelemetry-trace-soap]     Configure FAILURE
#7 84.77 [opentelemetry-trace-soap]     Activate FAILURE
#7 84.77 ERROR! Error copying directory /home/irisowner/dev/src/csp/ to /usr/irissys/csp/irisapp/
#7 84.77   > ERROR #5021: Directory '/home/irisowner/dev/src/csp/' does not exist.
#7 ERROR: process "/bin/sh -c iris start IRIS &&     iris merge IRIS merge.cpf && \tiris session IRIS < iris.script &
&     pip3 install -r requirements.txt &&     iris stop IRIS quietly" did not complete successfully: exit code: 1
------
 > [iris stage-0 3/3] RUN --mount=type=bind,src=.,dst=.     iris start IRIS &&     iris merge IRIS merge.cpf &&     i
ris session IRIS < iris.script &&     pip3 install -r requirements.txt &&     iris stop IRIS quietly:
84.77   > ERROR #5021: Directory '/home/irisowner/dev/src/csp/' does not exist.

------
failed to solve: process "/bin/sh -c iris start IRIS &&     iris merge IRIS merge.cpf && \tiris session IRIS < iris.s
cript &&     pip3 install -r requirements.txt &&     iris stop IRIS quietly" did not complete successfully: exit code
: 1

**Comment by pisani** [comment]
This should be resolved
